[package]
name = "tdigest"
version = "0.1.0"
authors = ["Jim Cooke <Jim.Cooke@coogee.email"]

[lib]
name = "tdigest"

[[bin]]
name = "tdigest"

[dependencies]
quickersort = "3.0"

[dev-dependencies]
assert_approx_eq = "1.0.0"
quickcheck = "0.6.2"